version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  env_file:
  - ./.env.dev
  volumes:
  - ./app:/app

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  env_file:
  - ./.env.db
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  - ./initdb.d:/docker-entrypoint-initdb.d #追記

volumes:
  mysql:
  mysql_config:
